title: "Hierarchical Vector Quantization for Intra-Phoneme Variability in Linguistic Representations"
description: "Demo Page"

url: "https://speechanonymous2026.github.io"
baseurl: "/phonemeawarervq"

remote_theme: "poole/hyde"
plugins:
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge